### Creating Arrays


In [42]:
import numpy as np

# 1D Array
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [43]:
print("Shape:",arr2.shape)
print("Size:", arr2.size)
print("Dimensions:", arr2.ndim)
print("Data Type:", arr2.dtype)
print("Item Size:", arr2.itemsize)


Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64
Item Size: 8


Some Useful Numpy Functions

In [44]:
# Creating an array of zeros
zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)

# Creating an array of ones
ones = np.ones((3, 2))
print("Ones:\n", ones)

# Creating a range of numbers
range_arr = np.arange(0, 10, 2)
print("Range array:", range_arr)

# Random numbers
rand_arr = np.random.rand(2, 2)
print("Random array:\n", rand_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range array: [0 2 4 6 8]
Random array:
 [[0.60214338 0.85506032]
 [0.86180447 0.11358787]]


In [45]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize)

# Adding 10 to all elements
arr_new = arr + 10
print("After adding 10:\n", arr_new)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64
Item Size: 8
After adding 10:
 [[11 12 13]
 [14 15 16]]
