### Creating Arrays


In [2]:
import numpy as np

# 1D Array
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
print("Shape:",arr2.shape)
print("Size:", arr2.size)
print("Dimensions:", arr2.ndim)
print("Data Type:", arr2.dtype)
print("Item Size:", arr2.itemsize)


Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64
Item Size: 8


### Some Useful Numpy Creative Functions

In [20]:
# Creating an array of zeros
zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)

# Creating an array of ones
ones = np.ones((3, 2))
print("Ones:\n", ones)

# Creating a range of numbers
range_arr = np.arange(0, 10, 2)
print("Range array:", range_arr)

# Random numbers
rand_arr = np.random.rand(2, 4)
print("Random array:\n", rand_arr)

eye = np.eye(3)
print("Eye:\n", eye)

linspace = np.linspace(0, 1, 5)
print(linspace)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range array: [0 2 4 6 8]
Random array:
 [[0.66112991 0.35669855 0.88344691 0.91883821]
 [0.75614762 0.4476772  0.52301059 0.44887402]]
Eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.   0.25 0.5  0.75 1.  ]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize)

# Adding 10 to all elements
arr_new = arr + 10
print("After adding 10:\n", arr_new)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64
Item Size: 8
After adding 10:
 [[11 12 13]
 [14 15 16]]


### Indexing and slicing

In [ ]:
arr = np.array([[23, 45, 6], [32, 76, 333], [34, 66, 68], [60, 9, 1]])
print(arr, "\n")

print(arr[:, 1]) # Everything on column 1 or all the rows on column 1
print(arr[2]) # Everything on row 2 or all the columns on row two
print(arr[0:2]) # Prints the first two rows

[[ 23  45   6]
 [ 32  76 333]
 [ 34  66  68]
 [ 60   9   1]] 

[45 76 66  9]
[34 66 68]
[[ 23  45   6]
 [ 32  76 333]]


### Mathematical functions

In [58]:
print("Print Square root:\n", np.sqrt(arr[3, 1]))
print("Print mean:\n", np.mean(arr))
print("Print Sum:\n", np.sum(arr[3]))
print("Print Minimum Number:\n", np.min(arr[2]))
print("Print Maximum Number:\n", np.max(arr[0]))
print("Standard Deviation:\n", np.std(arr[3]))

Print Square root:
 3.0
Print mean:
 62.75
Print Sum:
 70
Print Minimum Number:
 34
Print Maximum Number:
 45
Standard Deviation:
 26.132142830026186


### Shape Manipulation

In [66]:
print("Reshape Array:\n", arr.reshape(2, 6))
print("\nFlattens Array:\n", arr.flatten())
print("\nTransverse shape:\n", arr.T)


Reshape Array:
 [[ 23  45   6  32  76 333]
 [ 34  66  68  60   9   1]]

Flattens Array:
 [ 23  45   6  32  76 333  34  66  68  60   9   1]

Transverse shape:
 [[ 23  32  34  60]
 [ 45  76  66   9]
 [  6 333  68   1]]


### Brodcasting

In [73]:
print("Brodcast through:\n", arr + np.array([1, 2, 3]))


Brodcast through:
 [[ 24  47   9]
 [ 33  78 336]
 [ 35  68  71]
 [ 61  11   4]]
