### What is Numpy?
Numpy stands for Numeric Python.
It is a core library for numeric computation in python and the foundation of data science, machine learning, and AI workflows.

### Why is Numpy importatant?

- Much faster than Python lists
- Uses less memory
- Supports vectorized operations
- Designed for scientific computation

In [3]:
import numpy as np

Numbers = [[1, 2, 3], [4, 5, 6]]
Array = np.array([1, 2, 3, 4, 5])

print(Numbers)
print(Array)
converted = np.array(Numbers)
print(converted)


[[1, 2, 3], [4, 5, 6]]
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Numpy Array Attributes

In [ ]:
arr1 = np.array(["Sam", "David", "Joy", "Divine", "Ben", "Grace"])
arr2 = np.array([[1, 2, 3], [1, 2, 3], [1, 3, 4]])

print(arr1)
print(arr2)

print("Number of Dimension in Arr1:", arr1.ndim) # Number of Dimensions
print("Number of Dimension in Arr2:", arr2.ndim)

print(arr1.shape) # Shape of an Arra88 print(arr2.shape)

print(arr1.size) # total number of elements
print(arr2.size)

print(arr1.dtype) # data type
print(arr2.dtype)

['Sam' 'David' 'Joy' 'Divine' 'Ben' 'Grace']
[[1 2 3]
 [1 2 3]
 [1 3 4]]
Number of Dimension in Arr1: 1
Number of Dimension in Arr2: 2
(6,)
(3, 3)
6
9
<U6
int64
